-- Your SQL goes here
CREATE TABLE users (
  id VARCHAR(255) PRIMARY KEY,
  created_at BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  invite VARCHAR(255) REFERENCES invites(id)
)