name: api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  api:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt --check
    - name: clippy
      run: cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test ci --verbose
